version: '3.8'

services:
  travas-client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app

  travas-server:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    deploy:
      mode: replicated
      replicas: 1
    restart: always

  travas-nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    ports:
      - "5000:80"
    restart: always
